replicaCount: 1

image:
  repository: hnatekmarorg/lmproxy
  tag: latest
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: nginx
  host: lm-proxy.example.com
  tls:
    enabled: true
    secretName: lm-proxy-tls

config:
  server:
    port: 9090
  logging:
    level: info
    format: text
  endpoints: []
